x-watch-config: &python-watch
  watch:
    - action: sync+restart
      path: ./
      target: /app
      ignore:
        - ".venv/"
        - "__pycache__/"
        - ".git/"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uoft_courses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: docker.io/redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: always
    volumes:
      - redisinsight:/data

  rq-dashboard:
      image: eoranged/rq-dashboard:latest
      ports:
        - "9181:9181"
      environment:
        - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
      depends_on:
        - redis

  orchestrator:
    build: .
    develop: *python-watch
    restart: no
    env_file: .env
    command: python orchestrator.py
    depends_on:
      - redis
      - db

  # The Execution Engine
  course_info_worker:
    build: .
    develop: *python-watch
    restart: always
    env_file: .env
    command: rq worker course_info_queue
    depends_on:
      - redis
      - db
    deploy:
      replicas: 15
    stop_grace_period: 50s

  prereqs_worker:
    build: .
    develop: *python-watch
    restart: always
    env_file: .env
    command: rq worker prereqs_queue
    depends_on:
      - redis
      - db
    deploy:
      replicas: 5
    stop_grace_period: 60s

  program_worker:
    build: .
    develop: *python-watch
    restart: always
    env_file: .env
    command: rq worker program_queue
    depends_on:
      - redis
      - db
    deploy:
      replicas: 5
    stop_grace_period: 50s

volumes:
  pgdata:
  redisinsight: